add_lunch_combo cna_crespo-userdebug
add_lunch_combo cna_crespo4g-userdebug
add_lunch_combo cna_maguro-userdebug
add_lunch_combo cna_toro-userdebug
add_lunch_combo cna_stingray-userdebug
add_lunch_combo cna_wingray-userdebug
add_lunch_combo cna_galaxysmtd-userdebug
add_lunch_combo cna_inc-userdebug