add_lunch_combo cna_stock_captivatemtd-userdebug
add_lunch_combo cna_stock_crespo-userdebug
add_lunch_combo cna_stock_crespo4g-userdebug
add_lunch_combo cna_stock_epic4gtouch-userdebug
add_lunch_combo cna_stock_fascinatemtd-userdebug
add_lunch_combo cna_stock_galaxys2-userdebug
add_lunch_combo cna_stock_galaxysmtd-userdebug
add_lunch_combo cna_stock_i777-userdebug
add_lunch_combo cna_stock_stingray-userdebug
add_lunch_combo cna_stock_toro-userdebug
add_lunch_combo cna_stock_vibrantmtd-userdebug
add_lunch_combo cna_stock_wingray-userdebug

