add_lunch_combo cna_stock_crespo-userdebug
add_lunch_combo cna_stock_crespo4g-userdebug
add_lunch_combo cna_stock_stingray-userdebug
add_lunch_combo cna_stock_toro-userdebug
add_lunch_combo cna_stock_wingray-userdebug

